# SpringCloud feign 默认开启支持ribbon
ribbon:
  # 对所有操作请求都进行重试
  OkToRetryOnAllOperations: true
  # 请求连接的超时时间
  ConnectTimeout: 1000
  # 请求处理的超时时间
  ReadTimeout: 2000
  # 对当前实例的重试次数
  MaxAutoRetries: 2
  # 切换实例的重试次数
  MaxAutoRetriesNextServer: 1

hystrix:
  command:
    # 默认
    default:
    execution:
    timeout:
    enabled: true
    isolation:
    thread:
    # 断路器的超时时间需要大于ribbon的超时时间，不然不会触发重试。
    timeoutInMilliseconds: 8000

###开启Hystrix断路器
feign:
  hystrix:
    enabled: true

spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      # 自动更新表结构
      ddl-auto: update
    properties:
      hibernate:
        # 在控制台打出sql
        show_sql: true
  h2:
    console:
      enabled: true
      # 访问H2控制台的路径
      path: /h2/console
      settings:
        trace: false
        # 远程访问控制台
  web-allow-others: true

logging:
  level:
    root: info
    org:
      springframework:
        web: error
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace
              BasicExtractor: trace